### ISSUE TITLE
lib/ERC20 submodule not setup properly?

### ISSUE THREAD

**Issue by savil** [makerdao/testchain#27]
After `git clone`, i get the following error:

```
$ git submodule update --init --recursive
fatal: No url found for submodule path 'lib/ERC20' in .gitmodules
```

Also, eyeballing the folder structure of `lib/` in github, shows that ERC20 is displayed differently than the other submodules there.

**Comment by savil** [comment]
@ethanbennett seems like it was added in this commit https://github.com/makerdao/testchain/commit/262870b7f5701f93411d45bf2525079c801e478b . But something's not quite right?

**Comment by savil** [comment]
oh did there used to exist an ERC20 repo, which has now been deleted?

**Comment by ethanbennett** [comment]
@savil ERC20 actually isn't a submodule, but it seems to really confuse git. I've removed it repeatedly and it still seems to find its way back in when the repo is first cloned, so I should look into reorganizing this. Thanks for pointing it out--I haven't encountered it locally for a while, so I assumed the problem was solved.

In any case, it's a generic ERC20 token contract used as a stand-in on the testchain for the old MKR token. You can safely skip the update for it without affecting the testchain functionality.

**Comment by ethanbennett** [comment]
The ERC20 contract was replaced with DSToken, so this is no longer an issue.
