### ISSUE TITLE
Something wrong with scripts/create-snapshot DAI1

### ISSUE THREAD

**Issue by saramirabi** [makerdao/testchain#29]
Hi,
As i run
 scripts/launch --reset-chaindata -d -u
Testchain is already running on port 2000.
Press Ctrl-C to stop the testchain.
everything is fine but after that with 
scripts/create-snapshot default
tar: scripts/../var/chaindata: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
or 
scripts/create-snapshot NAME
tar: scripts/../var/chaindata: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

 It can not run.
I think something is missing?

**Comment by ethanbennett** [comment]
Hey, I'm seeing a few things that could be clearer in the docs and may have led to some misunderstandings here. Thanks for commenting.

First of all, have you added contracts to the deployment scripts? If not, and you just want to use the relevant Maker/Oasis contracts, you don't need to build, deploy, or create a snapshot. All you have to do is use the `default` snapshot, which in this case would look like:

```
scripts/launch -s default -u
```

However, if you're using it in the context of dai.js (I saw you have been working with that repo too, so I assume this is the case) you can just run `yarn testchain:fast` from the root of the dai.js monorepo.

However, just in case you are trying to rebuild and redeploy everything: your problem is coming from already having a testchain instance running in another terminal window. The script resets the chaindata as expected, but then it doesn't actually deploy anything, because it sees that ganache is already running and defaults to the existing instance. Resetting the chaindata clears `var/chaindata`, so when `create-snapshot` looks for those files, it can't find them. Just make sure you don't have a testchain already running when you execute `scripts/launch --reset-chaindata -d -u` and you should be good to go (however if you haven't already, be sure to run `git submodule update --init --recursive` first since `-u` skips that). But like I said, ignore this whole paragraph unless you're trying to add functionality beyond what you'd need for dai.js.
